on:
  schedule:    
    - cron:  '0 13 * * *'

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
           
jobs:  
  build:
      runs-on: ubuntu-latest
      permissions:
        contents: 'read'
        id-token: 'write'
     
      steps:
        - name: checkout repo content
          uses: actions/checkout@v3

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Google Auth
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
            
            

        - name: execute py script
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt            
            python app.py
            
